<html>
<head><meta charset="utf-8"><title>✔ Receiving error in docker &quot;Unable to pull &#x27;solr:9.4.1&#x27;&quot; · containers · Zulip Chat Archive</title></head>
<h2>Stream: <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/index.html">containers</a></h2>
<h3>Topic: <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/.E2.9C.94.20Receiving.20error.20in.20docker.20.22Unable.20to.20pull.20.27solr.3A9.2E4.2E1.27.22.html">✔ Receiving error in docker &quot;Unable to pull &#x27;solr:9.4.1&#x27;&quot;</a></h3>

<hr>

<base href="https://dataverse.zulipchat.com">

<head><link href="https://gdcc.github.io/zulip-archive/style.css" rel="stylesheet"></head>

<a name="474045008"></a>
<h4><a href="https://dataverse.zulipchat.com#narrow/stream/375812-containers/topic/%E2%9C%94%20Receiving%20error%20in%20docker%20%22Unable%20to%20pull%20%27solr%3A9.4.1%27%22/near/474045008" class="zl"><img src="https://gdcc.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Omer M Fahim <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/.E2.9C.94.20Receiving.20error.20in.20docker.20.22Unable.20to.20pull.20.27solr.3A9.2E4.2E1.27.22.html#474045008">(Oct 01 2024 at 13:57)</a>:</h4>
<p>Hello! When I run `mvn -Pct clean package docker:run I am receiving the following error:      </p>
<p>[<strong>ERROR</strong>] DOCKER&gt; Unable to pull 'solr:9.4.1' : {"message":"failed to resolve reference \"<a href="http://docker.io/library/solr:9.4.1\">docker.io/library/solr:9.4.1\</a>": failed to authorize: failed to fetch oauth token: unexpected status from GET request to <a href="https://auth.docker.io/token?scope=repository%3Alibrary%2Fsolr%3Apull&amp;service=registry.docker.io">https://auth.docker.io/token?scope=repository%3Alibrary%2Fsolr%3Apull&amp;service=registry.docker.io</a>: 401 Unauthorized"} (Internal Server Error: 500) [{"message":"failed to resolve reference \"<a href="http://docker.io/library/solr:9.4.1\">docker.io/library/solr:9.4.1\</a>": failed to authorize: failed to fetch oauth token: unexpected status from GET request to <a href="https://auth.docker.io/token?scope=repository%3Alibrary%2Fsolr%3Apull&amp;service=registry.docker.io">https://auth.docker.io/token?scope=repository%3Alibrary%2Fsolr%3Apull&amp;service=registry.docker.io</a>: 401 Unauthorized"} (Internal Server Error: 500)]</p>
<p>Has anyone come across this issue and know how to get past this?</p>



<a name="474047761"></a>
<h4><a href="https://dataverse.zulipchat.com#narrow/stream/375812-containers/topic/%E2%9C%94%20Receiving%20error%20in%20docker%20%22Unable%20to%20pull%20%27solr%3A9.4.1%27%22/near/474047761" class="zl"><img src="https://gdcc.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Oliver Bertuch <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/.E2.9C.94.20Receiving.20error.20in.20docker.20.22Unable.20to.20pull.20.27solr.3A9.2E4.2E1.27.22.html#474047761">(Oct 01 2024 at 14:09)</a>:</h4>
<p>Does this also happen to you when doing the pull manually? <code>docker pull docker.io/library/solr:9.4.1</code></p>



<a name="474047849"></a>
<h4><a href="https://dataverse.zulipchat.com#narrow/stream/375812-containers/topic/%E2%9C%94%20Receiving%20error%20in%20docker%20%22Unable%20to%20pull%20%27solr%3A9.4.1%27%22/near/474047849" class="zl"><img src="https://gdcc.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Oliver Bertuch <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/.E2.9C.94.20Receiving.20error.20in.20docker.20.22Unable.20to.20pull.20.27solr.3A9.2E4.2E1.27.22.html#474047849">(Oct 01 2024 at 14:09)</a>:</h4>
<p>If that doesn't work, I recommend to use <code>docker login</code> before starting to pull materials and try again</p>



<a name="474066792"></a>
<h4><a href="https://dataverse.zulipchat.com#narrow/stream/375812-containers/topic/%E2%9C%94%20Receiving%20error%20in%20docker%20%22Unable%20to%20pull%20%27solr%3A9.4.1%27%22/near/474066792" class="zl"><img src="https://gdcc.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Omer M Fahim <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/.E2.9C.94.20Receiving.20error.20in.20docker.20.22Unable.20to.20pull.20.27solr.3A9.2E4.2E1.27.22.html#474066792">(Oct 01 2024 at 15:34)</a>:</h4>
<p>when executing the pull manually I receive a similar error:     </p>
<p>View a summary of image vulnerabilities and recommendations → docker scout quickview <a href="http://docker.io/library/solr:9.4.1">docker.io/library/solr:9.4.1</a></p>
<p>Error response from daemon: failed to resolve reference "<a href="http://docker.io/library/solr:9.4.1">docker.io/library/solr:9.4.1</a>": failed to authorize: failed to fetch oauth token: unexpected status from GET request to <a href="https://auth.docker.io/token?scope=repository%3Alibrary%2Fsolr%3Apull&amp;service=registry.docker.io">https://auth.docker.io/token?scope=repository%3Alibrary%2Fsolr%3Apull&amp;service=registry.docker.io</a>: 401 Unauthorized</p>
<p>Also, I was logged in to the account.</p>



<a name="474345514"></a>
<h4><a href="https://dataverse.zulipchat.com#narrow/stream/375812-containers/topic/%E2%9C%94%20Receiving%20error%20in%20docker%20%22Unable%20to%20pull%20%27solr%3A9.4.1%27%22/near/474345514" class="zl"><img src="https://gdcc.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Omer M Fahim <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/.E2.9C.94.20Receiving.20error.20in.20docker.20.22Unable.20to.20pull.20.27solr.3A9.2E4.2E1.27.22.html#474345514">(Oct 02 2024 at 16:33)</a>:</h4>
<p>I was able to resolve this issue. Essentially what I did was uninstall Docker Desktop, install latest version, and signing out of my docker account.</p>



<a name="474525003"></a>
<h4><a href="https://dataverse.zulipchat.com#narrow/stream/375812-containers/topic/%E2%9C%94%20Receiving%20error%20in%20docker%20%22Unable%20to%20pull%20%27solr%3A9.4.1%27%22/near/474525003" class="zl"><img src="https://gdcc.github.io/zulip-archive/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Notification Bot <a href="https://gdcc.github.io/zulip-archive/stream/375812-containers/topic/.E2.9C.94.20Receiving.20error.20in.20docker.20.22Unable.20to.20pull.20.27solr.3A9.2E4.2E1.27.22.html#474525003">(Oct 03 2024 at 08:47)</a>:</h4>
<p><span class="user-mention silent" data-user-id="598183">Oliver Bertuch</span> has marked this topic as resolved.</p>



<hr><p>Last updated: Nov 01 2025 at 23:12 UTC</p>
</html>