[
    {
        "content": "<p>I am trying to make an API call to <a href=\"http://demo.dataverse.org\">demo.dataverse.org</a> to create a collection but receive an error <code>User @xxx is not permitted to perform requested action.</code> It would be nice if <code>https://demo.dataverse.org</code> supported testing of the API.  I'm trying to test a public API curation framework (<a href=\"https://github.com/kuhlaid/dv-api-test\">https://github.com/kuhlaid/dv-api-test</a>) that simplifies common Dataverse API actions and would like the public to be able to test easily. I can personally use the <code>https://demo-dataverse.rdmc.unc.edu</code> domain but am not sure if the public can use it to test API calls.</p>",
        "id": 505150776,
        "sender_full_name": "kuhlaid",
        "timestamp": 1741789957
    },
    {
        "content": "<p>Huh, it says \"Anyone with a Dataverse account can add sub dataverses and datasets\".</p>",
        "id": 505152143,
        "sender_full_name": "Philip Durbin 🚀",
        "timestamp": 1741790228
    },
    {
        "content": "<p><a href=\"/user_uploads/53090/ix6pBsfEaLaQdD6mrAqTTiBd/Screenshot-2025-03-12-at-10.37.15AM.png\">Screenshot 2025-03-12 at 10.37.15 AM.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/53090/ix6pBsfEaLaQdD6mrAqTTiBd/Screenshot-2025-03-12-at-10.37.15AM.png\" title=\"Screenshot 2025-03-12 at 10.37.15 AM.png\"><img data-original-content-type=\"image/png\" data-original-dimensions=\"1228x836\" src=\"/user_uploads/thumbnail/53090/ix6pBsfEaLaQdD6mrAqTTiBd/Screenshot-2025-03-12-at-10.37.15AM.png/840x560.webp\"></a></div>",
        "id": 505152238,
        "sender_full_name": "Philip Durbin 🚀",
        "timestamp": 1741790248
    },
    {
        "content": "<p>(As a side note, dv-api-test looks great! Please see also <a class=\"stream-topic\" data-stream-id=\"375707\" href=\"/#narrow/channel/375707-community/topic/recipes/with/503105735\">#community &gt; recipes</a>.)</p>",
        "id": 505152636,
        "sender_full_name": "Philip Durbin 🚀",
        "timestamp": 1741790324
    },
    {
        "content": "<p>Are you trying to create a collection in the root collection?</p>",
        "id": 505152762,
        "sender_full_name": "Philip Durbin 🚀",
        "timestamp": 1741790348
    },
    {
        "content": "<p>It should work! <span aria-label=\"sweat smile\" class=\"emoji emoji-1f605\" role=\"img\" title=\"sweat smile\">:sweat_smile:</span></p>",
        "id": 505152800,
        "sender_full_name": "Philip Durbin 🚀",
        "timestamp": 1741790354
    },
    {
        "content": "<p>Hi <span class=\"user-mention\" data-user-id=\"598112\">@Philip Durbin ☀️</span> , yes I'm trying to create a collection at the root when I receive the error. You are welcome to spin up the Notebook in MyBinder and test it yourself.</p>",
        "id": 505157434,
        "sender_full_name": "kuhlaid",
        "timestamp": 1741791301
    },
    {
        "content": "<p>Can you please try changing...</p>\n<div class=\"codehilite\"><pre><span></span><code>&quot;_cc__strDvApi_PARENT_COLLECTION&quot;: &quot;root&quot;,\n</code></pre></div>\n<p>... to...</p>\n<div class=\"codehilite\"><pre><span></span><code>&quot;_cc__strDvApi_PARENT_COLLECTION&quot;: &quot;:root&quot;,\n</code></pre></div>\n<p>...?</p>",
        "id": 505165096,
        "sender_full_name": "Philip Durbin 🚀",
        "timestamp": 1741792597
    },
    {
        "content": "<p>Done. That fixed the issue, thank you.</p>",
        "id": 505169520,
        "sender_full_name": "kuhlaid",
        "timestamp": 1741793480
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"670990\">kuhlaid</span> has marked this topic as resolved.</p>",
        "id": 505169596,
        "sender_full_name": "Notification Bot",
        "timestamp": 1741793492
    }
]