[
    {
        "content": "<p>Hey All, I'm having an issue with .tif thumbnails. They're currently coming out as zero-byte pngs and obviously not showing up properly<br>\n<a href=\"/user_uploads/53090/C0WJIVUkSecGAkE33ozI49BC/image.png\">image.png</a><br>\nI read in a ticket (<a href=\"https://github.com/IQSS/dataverse/issues/1738\">https://github.com/IQSS/dataverse/issues/1738</a>) about copying a library and restarting the web server, but that didn't help.</p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/53090/C0WJIVUkSecGAkE33ozI49BC/image.png\" title=\"image.png\"><img src=\"/user_uploads/53090/C0WJIVUkSecGAkE33ozI49BC/image.png\"></a></div><p>Any hints? Thanks.</p>",
        "id": 420098221,
        "sender_full_name": "Brian Cassidy",
        "timestamp": 1707240432
    },
    {
        "content": "<p>Hmm, the screenshot reminds me a lot of the ones here: Thumbnail display issues with .nii (NifTI) files <a href=\"https://github.com/IQSS/dataverse/issues/7080\">#7080</a></p>",
        "id": 420099837,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1707240944
    },
    {
        "content": "<p>FWIW, I'm seeing a lot of these messages from when the files were originally uploaded, but no real details:</p>\n<div class=\"codehilite\"><pre><span></span><code>[2024-02-06T12:46:12.031-0400] [Payara 5.2022.3] [WARNING] [] [edu.harvard.iq.dataverse.dataaccess.ImageThumbConverter] [tid:\n_ThreadID=94 _ThreadName=http-thread-pool::jk-connector(3)] [timeMillis: 1707237972031] [levelValue: 900] [[\n  caught Exceptiopn trying to create rescaled image /mnt/dataverse/temp/18d7f5010bd-5e512d218eb2.thumb64]]\n</code></pre></div>",
        "id": 420105047,
        "sender_full_name": "Brian Cassidy",
        "timestamp": 1707242756
    },
    {
        "content": "<p>oh interesting. i went to the last page, and some thumnails are there:<br>\n<a href=\"/user_uploads/53090/dImDFa9-a4g1X0JKnksba_4q/image.png\">image.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/53090/dImDFa9-a4g1X0JKnksba_4q/image.png\" title=\"image.png\"><img src=\"/user_uploads/53090/dImDFa9-a4g1X0JKnksba_4q/image.png\"></a></div>",
        "id": 420106615,
        "sender_full_name": "Brian Cassidy",
        "timestamp": 1707243306
    },
    {
        "content": "<p>there's a lot of files as you can see (2730)</p>",
        "id": 420106717,
        "sender_full_name": "Brian Cassidy",
        "timestamp": 1707243351
    },
    {
        "content": "<p>We've switched to a double-zipped file since he actually wants the zips to be the files presented.<br>\nSo, perhaps this was just a file limit issue -- we're working around it anyhow.</p>",
        "id": 420110646,
        "sender_full_name": "Brian Cassidy",
        "timestamp": 1707244723
    },
    {
        "content": "<p>Can you reproduce it on <a href=\"https://demo.dataverse.org\">https://demo.dataverse.org</a> ?</p>",
        "id": 420113900,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1707245717
    },
    {
        "content": "<p>eh, i'll have to get back to you on that. not sure i can upload all those files...</p>",
        "id": 420122703,
        "sender_full_name": "Brian Cassidy",
        "timestamp": 1707248882
    },
    {
        "content": "<p>Sure, no problem.</p>",
        "id": 420122786,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1707248904
    },
    {
        "content": "<p>Hi Philip, Brian,<br>\n  We had the same problem with two datasets. I have modified a file and upload it in the demo Dataverse portal: <a href=\"https://demo.dataverse.org/dataverse/pr\">https://demo.dataverse.org/dataverse/pr</a><br>\n  Our partial workaround was creating the thumbnails directly in the file system with the convert tool.</p>",
        "id": 421009507,
        "sender_full_name": "Juan",
        "timestamp": 1707737423
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"663397\">@Juan</span> interesting, thanks. I'm confused though. If it's a tiff, why does it have a .gif extension?</p>",
        "id": 421031149,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1707744739
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"598112\">@Philip Durbin</span> , I have made a mistake when I renamed the file. test.gif is a tiff. file. I have updated the dataset with the same file, but the right file extension and the same problem. <br>\n<a href=\"/user_uploads/53090/sx7vv28f4EiLd9ttV0EItyh3/imagen.png\">imagen.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/53090/sx7vv28f4EiLd9ttV0EItyh3/imagen.png\" title=\"imagen.png\"><img src=\"/user_uploads/53090/sx7vv28f4EiLd9ttV0EItyh3/imagen.png\"></a></div>",
        "id": 421043429,
        "sender_full_name": "Juan",
        "timestamp": 1707747396
    },
    {
        "content": "<p>Same md5. Same problem. Thanks!</p>",
        "id": 421048578,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1707748692
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"663397\">@Juan</span> would you (or <span class=\"user-mention\" data-user-id=\"670488\">@Brian Cassidy</span> ) be willing to create a GitHub issue about this? And attach that test2.tif file, please?</p>",
        "id": 421048928,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1707748787
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"598112\">@Philip Durbin</span>,  done: <a href=\"https://github.com/IQSS/dataverse/issues/10317\">https://github.com/IQSS/dataverse/issues/10317</a></p>",
        "id": 421064345,
        "sender_full_name": "Juan",
        "timestamp": 1707752421
    },
    {
        "content": "<p>Thank you! <span aria-label=\"heart\" class=\"emoji emoji-2764\" role=\"img\" title=\"heart\">:heart:</span></p>",
        "id": 421080223,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1707756546
    }
]