[
    {
        "content": "<p>Hi all, me again <span aria-label=\"wink\" class=\"emoji emoji-1f609\" role=\"img\" title=\"wink\">:wink:</span> </p>\n<p>I have upgraded my Dataverse version from 6.2 to 6.3. I have a problem when I create a new Dataset or Dataverse in my root Dataverse. When I create a new Dataset and publish it, it does not appear in my root Dataverse.</p>\n<p>This is what I have in my server.log</p>\n<div class=\"codehilite\"><pre><span></span><code>[2024-07-11T14:04:13.571-0500] [Payara 6.2024.6] [ADVERTENCIA] [] [edu.harvard.iq.dataverse.dataset.DatasetUtil] [tid: _ThreadID=76 _ThreadName=http-thread-pool::http-listener-1(4)] [timeMillis: 1720724653571] [levelValue: 900] [[\n  getThumbnail(): Failed to initialize dataset StorageIO for null (getDataAccessObject: null or invalid datafile.)]]\n\n[2024-07-11T14:04:13.571-0500] [Payara 6.2024.6] [ADVERTENCIA] [] [edu.harvard.iq.dataverse.dataset.DatasetUtil] [tid: _ThreadID=76 _ThreadName=http-thread-pool::http-listener-1(4)] [timeMillis: 1720724653571] [levelValue: 900] [[\n  getThumbnail(): Failed to initialize dataset StorageIO for null]]\n</code></pre></div>\n<p>I have created the JVM option <code>``&lt;jvm-options&gt;-Ddataverse.files.storage-driver-id=file&lt;/jvm-options&gt;</code>, but the problem continues.</p>",
        "id": 450791012,
        "sender_full_name": "Santiago Florez",
        "timestamp": 1720725818
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"652672\">@Santiago Florez</span> hi, I tweaked the subject of this thread a bit to make prevent it from being cut off. I hope you don't mind.</p>",
        "id": 450998438,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1720795736
    },
    {
        "content": "<p>Would you be able to share more of your server.log file?</p>",
        "id": 450998565,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1720795763
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"598112\">@Philip Durbin</span> Hi, </p>\n<p><span class=\"user-mention silent\" data-user-id=\"598112\">Philip Durbin</span> <a href=\"#narrow/stream/378866-troubleshooting/topic/datasets.20or.20collections.20created.20under.206.2E3.20do.20not.20appear/near/450998565\">ha dicho</a>:</p>\n<blockquote>\n<p>Would you be able to share more of your server.log file?</p>\n</blockquote>\n<p>Those are the only two warning lines when I try to create a Dataset. The Datasets and subdataverses are created correctly, but when I access the Dataverse Root, the Dataverse where I create them, I do not see them.</p>\n<p>An image of the server.log file<br>\n<a href=\"/user_uploads/53090/yRlF7lu8FZWIpxKfwQTORQ4E/image.png\">image.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/53090/yRlF7lu8FZWIpxKfwQTORQ4E/image.png\" title=\"image.png\"><img src=\"/user_uploads/53090/yRlF7lu8FZWIpxKfwQTORQ4E/image.png\"></a></div><p>An image of the Dataset I have created.<br>\n<a href=\"/user_uploads/53090/dDwKfaxpJ-pz6mKYt9IyUA1n/image.png\">image.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/53090/dDwKfaxpJ-pz6mKYt9IyUA1n/image.png\" title=\"image.png\"><img src=\"/user_uploads/53090/dDwKfaxpJ-pz6mKYt9IyUA1n/image.png\"></a></div><p>An image of Dataverse root<br>\n<a href=\"/user_uploads/53090/qmSIsHiT4lhDmjgejXHIdfsO/image.png\">image.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/53090/qmSIsHiT4lhDmjgejXHIdfsO/image.png\" title=\"image.png\"><img src=\"/user_uploads/53090/qmSIsHiT4lhDmjgejXHIdfsO/image.png\"></a></div>",
        "id": 451027972,
        "sender_full_name": "Santiago Florez",
        "timestamp": 1720803221
    },
    {
        "content": "<p>Hmm, did you upgrade Solr as part of the 6.3 upgrade?</p>",
        "id": 451041524,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1720807636
    },
    {
        "content": "<p>Hi Philip, I have also updated the solr.</p>",
        "id": 451636467,
        "sender_full_name": "Santiago Florez",
        "timestamp": 1721080077
    },
    {
        "content": "<p>Did that help?</p>",
        "id": 451759929,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1721136773
    },
    {
        "content": "<p>Hi Philip, when I updated Solr I forgot to create the core collection1, so I have created it and everything ok. Thanks</p>",
        "id": 451798271,
        "sender_full_name": "Santiago Florez",
        "timestamp": 1721146194
    },
    {
        "content": "<p>Fantastic! <span aria-label=\"tada\" class=\"emoji emoji-1f389\" role=\"img\" title=\"tada\">:tada:</span></p>",
        "id": 451806924,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1721148203
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"598112\">Philip Durbin</span> has marked this topic as resolved.</p>",
        "id": 451806936,
        "sender_full_name": "Notification Bot",
        "timestamp": 1721148207
    }
]