[
    {
        "content": "<p>Dear DV experts: </p>\n<p>We installed dataverse and used to be able to create datasets with the FAKE doi setting. But after configuring with our datacite account, I got a error message after clicking on \"save dataset\":</p>\n<p>XML Parsing Error: not well-formed<br>\nLocation: <a href=\"https://dataverse.fgcu.edu/dataset.xhtml?persistentId=doi%3A10.60863%2FSF%2FJ4JRE9&amp;version=DRAFT\">https://dataverse.fgcu.edu/dataset.xhtml?persistentId=doi%3A10.60863%2FSF%2FJ4JRE9&amp;version=DRAFT</a><br>\nLine Number 226, Column 17:<br>\n        &lt;/div&gt;&lt;!DOCTYPE html&gt;<br>\n----------------^</p>\n<p>I have checked the domain.xml settings and did not find obvious problems as shown below. <br>\n-Ddataverse.pid.datacite.mds-api-url=https://mds.datacite.org<br>\n-Ddataverse.pid.datacite.username=OUR.ACCOUNT<br>\n-Ddataverse.pid.datacite.rest-api-url=https://api.datacite.org<br>\ncurl <a href=\"http://localhost:8080/api/admin/settings/:Authority\">http://localhost:8080/api/admin/settings/:Authority</a> -w \"\\n\" <br>\n{\"status\":\"OK\",\"data\":{\"message\":\"10.60863\"}}<br>\ncurl <a href=\"http://localhost:8080/api/admin/settings/:DoiProvider\">http://localhost:8080/api/admin/settings/:DoiProvider</a> -w \"\\n\" <br>\n{\"status\":\"OK\",\"data\":{\"message\":\"DataCite\"}}<br>\ncurl <a href=\"http://localhost:8080/api/admin/settings/:Protocol\">http://localhost:8080/api/admin/settings/:Protocol</a> -w \"\\n\" <br>\n{\"status\":\"OK\",\"data\":{\"message\":\"doi\"}}</p>\n<p>Here is the server log:<br>\n<a href=\"/user_uploads/53090/6ql4-aZR0iNW8PhS2Xnknvne/server.log\">server.log</a></p>\n<p>I have tested our Datacite account on <a href=\"https://doi.datacite.org/\">https://doi.datacite.org/</a> and can successfully log in, but there is no record of any DOI. I also checked the PostgreSQL database and nothing was saved after clicking on \"save dataset\".  We installed PostgreSQL on one server and everything else on another server. I have checked both servers. They have no problems connecting to each other and I have no problems creating new sub-dataverse. I ran out of ideas of where the \"Username may not be null\" error comes from. The one thing I am not sure is that we moved both servers and got new IP addresses for them after installation. Could this cause the problem? Thank you in advance for reading and helping.</p>",
        "id": 399802673,
        "sender_full_name": "Hansen C.",
        "timestamp": 1698872414
    },
    {
        "content": "<p>Hi! What version of Dataverse are you running, please? It looks like 5.13?</p>",
        "id": 399803450,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1698872693
    },
    {
        "content": "<p>I see you found the \"Username may not be null\" error already.</p>",
        "id": 399803470,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1698872704
    },
    {
        "content": "<p>Here's the line from your logs: <a href=\"https://github.com/IQSS/dataverse/blob/v5.13/src/main/java/edu/harvard/iq/dataverse/DataCiteRESTfullClient.java#L53\">https://github.com/IQSS/dataverse/blob/v5.13/src/main/java/edu/harvard/iq/dataverse/DataCiteRESTfullClient.java#L53</a></p>",
        "id": 399803657,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1698872806
    },
    {
        "content": "<p>Hi Philip, Yes, it is 5.13. <a href=\"https://dataverse.fgcu.edu/\">https://dataverse.fgcu.edu/</a>.</p>",
        "id": 399804282,
        "sender_full_name": "Hansen C.",
        "timestamp": 1698873111
    },
    {
        "content": "<p>It seems the DataCiteRESTfullClient did not pick up our Datacite username.</p>",
        "id": 399804540,
        "sender_full_name": "Hansen C.",
        "timestamp": 1698873240
    },
    {
        "content": "<p>I'm looking at <a href=\"https://guides.dataverse.org/en/5.13/installation/config.html#doi-username\">https://guides.dataverse.org/en/5.13/installation/config.html#doi-username</a></p>",
        "id": 399804632,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1698873282
    },
    {
        "content": "<p>It seems to want <code>-Ddoi.username=YOUR_USERNAME_HERE</code></p>",
        "id": 399804654,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1698873296
    },
    {
        "content": "<p>But you have <code>-Ddataverse.pid.datacite.username=OUR.ACCOUNT</code>?</p>",
        "id": 399804804,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1698873370
    },
    {
        "content": "<p>I got <a href=\"https://guides.dataverse.org/en/latest/installation/config.html?highlight=datacite#dataverse-pid-datacite-username\">https://guides.dataverse.org/en/latest/installation/config.html?highlight=datacite#dataverse-pid-datacite-username</a></p>",
        "id": 399804967,
        "sender_full_name": "Hansen C.",
        "timestamp": 1698873477
    },
    {
        "content": "<p>I though Ddoi was replaced. Do I still need it?</p>",
        "id": 399805064,
        "sender_full_name": "Hansen C.",
        "timestamp": 1698873509
    },
    {
        "content": "<p>Maybe, but \"latest\" is for 6.0. The link I posted is for 5.13.</p>",
        "id": 399805146,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1698873575
    },
    {
        "content": "<p>Thanks a lot! I think that's the reason.</p>",
        "id": 399805247,
        "sender_full_name": "Hansen C.",
        "timestamp": 1698873630
    },
    {
        "content": "<p>That is, \"latest\" is for the latest release, which is currently 6.0. <span aria-label=\"grinning\" class=\"emoji emoji-1f600\" role=\"img\" title=\"grinning\">:grinning:</span></p>",
        "id": 399805248,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1698873631
    },
    {
        "content": "<p>Sure! Hope it helps.</p>",
        "id": 399805267,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1698873640
    },
    {
        "content": "<p>I installed Dataverse in July and did not see 6.0. Where can I find it?</p>",
        "id": 399805345,
        "sender_full_name": "Hansen C.",
        "timestamp": 1698873678
    },
    {
        "content": "<p>Thank you so much! It puzzled me for a week. You saved my life <span aria-label=\"grinning face with smiling eyes\" class=\"emoji emoji-1f601\" role=\"img\" title=\"grinning face with smiling eyes\">:grinning_face_with_smiling_eyes:</span></p>",
        "id": 399805501,
        "sender_full_name": "Hansen C.",
        "timestamp": 1698873767
    },
    {
        "content": "<p>Ha! Good!</p>",
        "id": 399805591,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1698873824
    },
    {
        "content": "<p>6.0 is here: <a href=\"https://github.com/IQSS/dataverse/releases/tag/v6.0\">https://github.com/IQSS/dataverse/releases/tag/v6.0</a></p>",
        "id": 399805610,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1698873837
    },
    {
        "content": "<p>Got it. Have a great evening!</p>",
        "id": 399805684,
        "sender_full_name": "Hansen C.",
        "timestamp": 1698873868
    }
]