[
    {
        "content": "<p>Hey everybody. I already obened a conversation here <a href=\"https://groups.google.com/g/dataverse-community/c/wL6Q2bsvw04/m/4KDBFk1IAgAJ?utm_medium=email&amp;utm_source=footer\">https://groups.google.com/g/dataverse-community/c/wL6Q2bsvw04/m/4KDBFk1IAgAJ?utm_medium=email&amp;utm_source=footer</a> but it is hard to find the reason, why the deployment failed. Maybe it is better in zulip.<br>\nShort summary: In the console I entered python3 install.py. Everthing worked fine and when it tryed to deploy the dataverse.war file I got this output <br>\n'No response from Domain Admin Server after 600 seconds.<br>\nThe command is either taking too long to complete or the server has failed.<br>\nPlease see the server log files for command status.<br>\nCommand deploy failed.<br>\nFailed to deploy the application!'  <br>\n But then when I look into the payara admin console I see the deployed dataverse war. But I cannot open localhost:8080. What happend there? <br>\nCan anybody help me? <br>\n<a href=\"/user_uploads/53090/WqPXxbL0j_b4LgcEqPFzpvxy/server.log\">server.log</a><br>\n<a href=\"/user_uploads/53090/0pob6IGZ9btapa2efXirNvz5/2024-01-12_14h07_18.png\">2024-01-12_14h07_18.png</a><br>\n<a href=\"/user_uploads/53090/BbwaUecX8oZLO9LRPwKAUzR4/2024-01-12_14h06_34.png\">2024-01-12_14h06_34.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/53090/0pob6IGZ9btapa2efXirNvz5/2024-01-12_14h07_18.png\" title=\"2024-01-12_14h07_18.png\"><img src=\"/user_uploads/53090/0pob6IGZ9btapa2efXirNvz5/2024-01-12_14h07_18.png\"></a></div><div class=\"message_inline_image\"><a href=\"/user_uploads/53090/BbwaUecX8oZLO9LRPwKAUzR4/2024-01-12_14h06_34.png\" title=\"2024-01-12_14h06_34.png\"><img src=\"/user_uploads/53090/BbwaUecX8oZLO9LRPwKAUzR4/2024-01-12_14h06_34.png\"></a></div>",
        "id": 416538698,
        "sender_full_name": "Su Sa",
        "timestamp": 1705572833
    },
    {
        "content": "<p>Hi! Thanks for joining.</p>",
        "id": 416561879,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705581259
    },
    {
        "content": "<p>What do you get if you go to <a href=\"http://localhost:8080/api/info/version\">http://localhost:8080/api/info/version</a> ?</p>",
        "id": 416561906,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705581268
    },
    {
        "content": "<p>{<br>\n    \"status\": \"OK\",<br>\n    \"data\": {<br>\n        \"version\": \"6.0\",<br>\n        \"build\": \"1512-366fd41\"<br>\n    }<br>\n}</p>",
        "id": 416562802,
        "sender_full_name": "Su Sa",
        "timestamp": 1705581593
    },
    {
        "content": "<p>ah, hi philip, its you. cool</p>",
        "id": 416563126,
        "sender_full_name": "Su Sa",
        "timestamp": 1705581707
    },
    {
        "content": "<p>Ok, so the war file has definitely been deployed.</p>",
        "id": 416563134,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705581708
    },
    {
        "content": "<p>How about <a href=\"http://localhost:8080/api/metadatablocks\">http://localhost:8080/api/metadatablocks</a> ?</p>",
        "id": 416563287,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705581752
    },
    {
        "content": "<p>yes I also think so. but so console say it wasn't  deployed</p>",
        "id": 416563289,
        "sender_full_name": "Su Sa",
        "timestamp": 1705581754
    },
    {
        "content": "<p>{<br>\n    \"status\": \"OK\",<br>\n    \"data\": []<br>\n}</p>",
        "id": 416563381,
        "sender_full_name": "Su Sa",
        "timestamp": 1705581788
    },
    {
        "content": "<p>Ok, that's bad. It should have a lot of data, like this: <a href=\"https://demo.dataverse.org/api/metadatablocks\">https://demo.dataverse.org/api/metadatablocks</a></p>",
        "id": 416563455,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705581816
    },
    {
        "content": "<p>How attached are you to this installation? Can we throw it away and start again?</p>",
        "id": 416563574,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705581854
    },
    {
        "content": "<p>yes, thats no problem. we can install everything from the beginning</p>",
        "id": 416563920,
        "sender_full_name": "Su Sa",
        "timestamp": 1705581970
    },
    {
        "content": "<p>Great. What flavor of Linux are you using? Rocky? Ubuntu?</p>",
        "id": 416564313,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705582107
    },
    {
        "content": "<p>neither nor  I use debian</p>",
        "id": 416565139,
        "sender_full_name": "Su Sa",
        "timestamp": 1705582434
    },
    {
        "content": "<p>Ok. RHEL/Rocky is the preferred distro but Ubuntu/Debian should work.</p>",
        "id": 416566424,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705582858
    },
    {
        "content": "<p>I suspect that the bootstrap wasn't successful</p>",
        "id": 416566694,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1705582940
    },
    {
        "content": "<p>These are the recommended steps for a fresh reinstall: <a href=\"https://guides.dataverse.org/en/6.0/installation/installation-main.html#fresh-reinstall\">https://guides.dataverse.org/en/6.0/installation/installation-main.html#fresh-reinstall</a></p>",
        "id": 416566724,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705582950
    },
    {
        "content": "<p>I've seen exactly this behaviour with <span class=\"user-mention\" data-user-id=\"675921\">@Jutta Schnabel</span>'s deployment</p>",
        "id": 416566833,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1705582986
    },
    {
        "content": "<p>Well, this is not in containers.</p>",
        "id": 416566904,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705583004
    },
    {
        "content": "<p>WAR successfully deployed (themed 404 error and /api/info), but nothing else works</p>",
        "id": 416566959,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1705583015
    },
    {
        "content": "<p>True, but the symptoms are the same</p>",
        "id": 416566992,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1705583023
    },
    {
        "content": "<p>Maybe not the reason</p>",
        "id": 416567015,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1705583029
    },
    {
        "content": "<p>yeah</p>",
        "id": 416567084,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705583043
    },
    {
        "content": "<p>I've been trying to get more output. To see what is going wrong.</p>",
        "id": 416567209,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705583067
    },
    {
        "content": "<p><a href=\"https://guides.dataverse.org/en/6.0/installation/installation-main.html#fresh-reinstall\">https://guides.dataverse.org/en/6.0/installation/installation-main.html#fresh-reinstall</a> i do this for more than 5 times</p>",
        "id": 416567495,
        "sender_full_name": "Su Sa",
        "timestamp": 1705583153
    },
    {
        "content": "<p>Probably the result is not going to be a different one then <span aria-label=\"wink\" class=\"emoji emoji-1f609\" role=\"img\" title=\"wink\">:wink:</span></p>",
        "id": 416567615,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1705583185
    },
    {
        "content": "<p>Could you provide a server.log and output from the installer from one of the attempts?</p>",
        "id": 416567654,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1705583205
    },
    {
        "content": "<p>That would be really helpful in trying to corner reasons why things blow up</p>",
        "id": 416567671,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1705583219
    },
    {
        "content": "<p>(If these filenames and things mean nothing to you, let us know - happy to explain more)</p>",
        "id": 416567766,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1705583261
    },
    {
        "content": "<p>One of the five server.log's is above.</p>",
        "id": 416567922,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705583312
    },
    {
        "content": "<p>I've been trying to get output from the terminal and setup logs: <a href=\"https://guides.dataverse.org/en/6.0/installation/intro.html#information-to-send-to-support-when-installation-fails\">https://guides.dataverse.org/en/6.0/installation/intro.html#information-to-send-to-support-when-installation-fails</a></p>",
        "id": 416567968,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705583341
    },
    {
        "content": "<p>Installer log would be perfect - if some of the scripts fail, that might not be visible from the Payara logs</p>",
        "id": 416567975,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1705583343
    },
    {
        "content": "<p>gotta bike through the ice... back soon</p>",
        "id": 416568063,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705583386
    },
    {
        "content": "<p>Break a leg!</p>",
        "id": 416568082,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1705583395
    },
    {
        "content": "<p>yes that would be no problem. I converted the server.log to fine should i return that?</p>",
        "id": 416568466,
        "sender_full_name": "Su Sa",
        "timestamp": 1705583526
    },
    {
        "content": "<p>what ist 'output from the installer from one of the attempts?'</p>",
        "id": 416568673,
        "sender_full_name": "Su Sa",
        "timestamp": 1705583611
    },
    {
        "content": "<p>'The scripts/api/setup-all.*.log files left behind by the installer.' this files are not genered. if I look into the install.py i can see, that this files will be genereted after deploying of the war. I thing its not generedet because it interrupt the installing process before it will generate this files.</p>",
        "id": 416569258,
        "sender_full_name": "Su Sa",
        "timestamp": 1705583817
    },
    {
        "content": "<p>I got an error when I tried to drop the database<br>\n'psql: Error: Connection to server failed on socket '/var/run/postgresql/.s.PGSQL.5432': FATAL: Peer authentication failed for user 'dvnapp''</p>",
        "id": 416570843,
        "sender_full_name": "Su Sa",
        "timestamp": 1705584361
    },
    {
        "content": "<p>Hmm, I wonder if the database was ever created. If not, there's nothing to drop.</p>",
        "id": 416575935,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705586129
    },
    {
        "content": "<p>ok, how can i check it?</p>",
        "id": 416576921,
        "sender_full_name": "Su Sa",
        "timestamp": 1705586442
    },
    {
        "content": "<div class=\"codehilite\"><pre><span></span><code>[postgres@ip-172-31-5-10 ~]$ psql\npsql (13.9)\nType &quot;help&quot; for help.\n\npostgres=# \\l\n                                  List of databases\n   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges\n-----------+----------+----------+-------------+-------------+-----------------------\n dvndb     | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =Tc/postgres         +\n           |          |          |             |             | postgres=CTc/postgres+\n           |          |          |             |             | dvnuser=CTc/postgres\n postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |\n template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +\n           |          |          |             |             | postgres=CTc/postgres\n template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +\n           |          |          |             |             | postgres=CTc/postgres\n(4 rows)\n\npostgres=#\n</code></pre></div>",
        "id": 416577426,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705586582
    },
    {
        "content": "<p>Something like that. ^^</p>",
        "id": 416577443,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705586587
    },
    {
        "content": "<p>The database is called \"dvndb\".</p>",
        "id": 416577467,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705586593
    },
    {
        "content": "<p>yes i check it. but I saw this before</p>",
        "id": 416577627,
        "sender_full_name": "Su Sa",
        "timestamp": 1705586642
    },
    {
        "content": "<p>but now nothing happen. Only this error appears.</p>",
        "id": 416577770,
        "sender_full_name": "Su Sa",
        "timestamp": 1705586682
    },
    {
        "content": "<p>Can you drop the \"dvndb\" database using the \"postgres\" user instead of the \"dvnapp\" user?</p>",
        "id": 416577957,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705586742
    },
    {
        "content": "<p>Also, apologies, but I need to run a meeting soon. You're welcome to join if you like: <a class=\"stream-topic\" data-stream-id=\"375812\" href=\"/#narrow/stream/375812-containers/topic/weekly.20meeting\">#containers &gt; weekly meeting</a></p>",
        "id": 416578140,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705586782
    },
    {
        "content": "<p>no problem. then we go on later.</p>",
        "id": 416578347,
        "sender_full_name": "Su Sa",
        "timestamp": 1705586850
    },
    {
        "content": "<p>Also, even if the setup log files can't be found, you see output on your terminal, right? When you run install.py.</p>",
        "id": 416578616,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705586922
    },
    {
        "content": "<p>yes i see</p>",
        "id": 416579113,
        "sender_full_name": "Su Sa",
        "timestamp": 1705587065
    },
    {
        "content": "<p>Can you please share that output?</p>",
        "id": 416579148,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705587079
    },
    {
        "content": "<p>yes now it says performing database setup<br>\nAdmin database connectivity succeeds.<br>\nPostgreSQL version: 13<br>\nLooks like the user already exists. Continuing.<br>\nCouldn't create database or database already exists.</p>",
        "id": 416579561,
        "sender_full_name": "Su Sa",
        "timestamp": 1705587212
    },
    {
        "content": "<p>now something went wrong with the database</p>",
        "id": 416579600,
        "sender_full_name": "Su Sa",
        "timestamp": 1705587230
    },
    {
        "content": "<p>ok, I think we have to go on tomorow. I have to pick up my kids.....</p>",
        "id": 416580088,
        "sender_full_name": "Su Sa",
        "timestamp": 1705587387
    },
    {
        "content": "<p>Sounds good. I'm taking a day off tomorrow but I'm happy to help on Monday.</p>",
        "id": 416580773,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705587605
    },
    {
        "content": "<p>Good morning. A miracle has happened. I deleted the database manually and the install.py could run throught to the end. I tried a lot to delete the dvndb but there was no way. Both the dnvapp and the postgres were not allowed to delete the dvndb. I disable all the access restrictions on localhost connections in the pg_hba.conf.</p>",
        "id": 417187785,
        "sender_full_name": "Su Sa",
        "timestamp": 1705915617
    },
    {
        "content": "<p>... and now everything is working? You can log into Dataverse? You can create a dataset?</p>",
        "id": 417215216,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705925175
    },
    {
        "content": "<p>No, unfortunately not yet. I can log into Dataverse, but then I see this errors. <br>\n<a href=\"/user_uploads/53090/50qxiEtXNk12ihdcitWXD2Qs/2024-01-23_10h46_41.png\">2024-01-23_10h46_41.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/53090/50qxiEtXNk12ihdcitWXD2Qs/2024-01-23_10h46_41.png\" title=\"2024-01-23_10h46_41.png\"><img src=\"/user_uploads/53090/50qxiEtXNk12ihdcitWXD2Qs/2024-01-23_10h46_41.png\"></a></div>",
        "id": 417407322,
        "sender_full_name": "Su Sa",
        "timestamp": 1706003287
    },
    {
        "content": "<p>Did you install Solr? Is it running? Can you query Solr outside of Dataverse?</p>",
        "id": 417432195,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1706011790
    },
    {
        "content": "<p>yes i istalled it. and it seems to be not running <br>\n<a href=\"/user_uploads/53090/8rZYSuRTl5oGDTcpeW6eZtDc/image.png\">image.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/53090/8rZYSuRTl5oGDTcpeW6eZtDc/image.png\" title=\"image.png\"><img src=\"/user_uploads/53090/8rZYSuRTl5oGDTcpeW6eZtDc/image.png\"></a></div>",
        "id": 417443585,
        "sender_full_name": "Su Sa",
        "timestamp": 1706015880
    },
    {
        "content": "<p>What if you curl <a href=\"http://localhost:8983/solr/collection1/schema/fields\">http://localhost:8983/solr/collection1/schema/fields</a> ? What do you get?</p>",
        "id": 417448183,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1706017470
    },
    {
        "content": "<p>ERR_CONNECTION_REFUSED</p>",
        "id": 417449916,
        "sender_full_name": "Su Sa",
        "timestamp": 1706017967
    },
    {
        "content": "<p>the site is not availabe</p>",
        "id": 417450019,
        "sender_full_name": "Su Sa",
        "timestamp": 1706017999
    },
    {
        "content": "<p>Hmm, sounds like we need to fix Solr. I assume you've tried stopping and starting it again. Maybe reinstall it?</p>",
        "id": 417454801,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1706019384
    },
    {
        "content": "<p>hmmm, yes something went wrong with my solr<br>\nI started and stoped it but the when I asked for the status the solr is offline<br>\nHow can I reinstall it?</p>",
        "id": 417635457,
        "sender_full_name": "Su Sa",
        "timestamp": 1706099539
    },
    {
        "content": "<p><a href=\"/user_uploads/53090/kuW9SzyTotzD_0aGGt9iSnCn/image.png\">image.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/53090/kuW9SzyTotzD_0aGGt9iSnCn/image.png\" title=\"image.png\"><img src=\"/user_uploads/53090/kuW9SzyTotzD_0aGGt9iSnCn/image.png\"></a></div>",
        "id": 417636044,
        "sender_full_name": "Su Sa",
        "timestamp": 1706099786
    },
    {
        "content": "<p>I would stop it, rm -rf the directory, and then try again: <a href=\"https://guides.dataverse.org/en/6.1/installation/prerequisites.html#solr\">https://guides.dataverse.org/en/6.1/installation/prerequisites.html#solr</a></p>",
        "id": 417644949,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1706102786
    },
    {
        "content": "<p>At this point, I'd feel remiss if I didn't point out you could let Ansible install Dataverse for you. Please see <a href=\"https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible#quickstart\">https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible#quickstart</a></p>\n<p>It was created and is maintained by <span class=\"user-mention\" data-user-id=\"626369\">@Don Sizemore</span> and we use it all the time in our continuous integration (CI) testing.</p>",
        "id": 417645252,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1706102894
    },
    {
        "content": "<p><a href=\"/user_uploads/53090/Dvy1ZiuaaaUJ0Zdk6I-aC3yO/image.png\">image.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/53090/Dvy1ZiuaaaUJ0Zdk6I-aC3yO/image.png\" title=\"image.png\"><img src=\"/user_uploads/53090/Dvy1ZiuaaaUJ0Zdk6I-aC3yO/image.png\"></a></div>",
        "id": 417652654,
        "sender_full_name": "Su Sa",
        "timestamp": 1706105293
    },
    {
        "content": "<p>shit don't work. I remove everything and make it new. but same result</p>",
        "id": 417653348,
        "sender_full_name": "Su Sa",
        "timestamp": 1706105507
    },
    {
        "content": "<p>yes, i see ansible. mybe thats a good idea.</p>",
        "id": 417653579,
        "sender_full_name": "Su Sa",
        "timestamp": 1706105583
    },
    {
        "content": "<p>ha, i got it. yyyeeeeaaaahhhh. I have to change the jetty host to 0.0.0.0. but what I do not do was to delete the comment out. small cause big effect</p>",
        "id": 417655178,
        "sender_full_name": "Su Sa",
        "timestamp": 1706106107
    },
    {
        "content": "<p>so next step I try to upload some datas</p>",
        "id": 417655419,
        "sender_full_name": "Su Sa",
        "timestamp": 1706106182
    },
    {
        "content": "<p>Shoot, the jetty 0.0.0.0 thing. That's a definite gotcha. <span class=\"user-mention\" data-user-id=\"626369\">@Don Sizemore</span> let us know about it.</p>",
        "id": 417656207,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1706106409
    },
    {
        "content": "<p>... and fixed it in this PR: document localhost-only behavior of Solr-9.3.0 and later <a href=\"https://github.com/IQSS/dataverse/issues/10037\">#10037</a></p>",
        "id": 417656487,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1706106503
    },
    {
        "content": "<p>is there a way to figure out why I cannot upload some datas?</p>",
        "id": 418268074,
        "sender_full_name": "Su Sa",
        "timestamp": 1706273017
    },
    {
        "content": "<p>Oh! Sounds like you're making progress. You can create a dataset at least?</p>",
        "id": 418275619,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1706275779
    },
    {
        "content": "<p>Which files can be uploaded? Which can't?</p>",
        "id": 418275664,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1706275800
    },
    {
        "content": "<p>Yes, a little bit. :P I can creat a dataverse but I cannot uplaod datasets</p>",
        "id": 418276168,
        "sender_full_name": "Su Sa",
        "timestamp": 1706276003
    },
    {
        "content": "<p>What do you see in server.log?</p>",
        "id": 418276230,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1706276034
    },
    {
        "content": "<p>Where is it hidden again?</p>",
        "id": 418276638,
        "sender_full_name": "Su Sa",
        "timestamp": 1706276190
    },
    {
        "content": "<p><a href=\"https://guides.dataverse.org/en/6.1/admin/troubleshooting.html#finding-the-payara-log-file\">https://guides.dataverse.org/en/6.1/admin/troubleshooting.html#finding-the-payara-log-file</a></p>",
        "id": 418276703,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1706276217
    },
    {
        "content": "<p>ah glassfish domain 1. I got it</p>",
        "id": 418276792,
        "sender_full_name": "Su Sa",
        "timestamp": 1706276247
    },
    {
        "content": "<p>ha, now its available... crazy. I tried to uplaod it yesterday but the page was frozen. Now the dataset is available.... confusing but great</p>",
        "id": 418277708,
        "sender_full_name": "Su Sa",
        "timestamp": 1706276631
    },
    {
        "content": "<p>there is no new server log since last week friday</p>",
        "id": 418277920,
        "sender_full_name": "Su Sa",
        "timestamp": 1706276714
    },
    {
        "content": "<p>not perfect but great to hear! <span aria-label=\"tada\" class=\"emoji emoji-1f389\" role=\"img\" title=\"tada\">:tada:</span></p>",
        "id": 418277921,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1706276714
    },
    {
        "content": "<p>yes, I have to play a litte bit and observe the theme</p>",
        "id": 418278028,
        "sender_full_name": "Su Sa",
        "timestamp": 1706276758
    },
    {
        "content": "<p>Well, please keep the questions coming. And please start a new topic (here in Zulip) as needed.</p>",
        "id": 418279799,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1706277305
    }
]