[
    {
        "content": "<p>See <a href=\"https://github.com/conda-forge/pydataverse-feedstock/pull/4#issuecomment-2404720792\">https://github.com/conda-forge/pydataverse-feedstock/pull/4#issuecomment-2404720792</a></p>",
        "id": 476222047,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1728593311
    },
    {
        "content": "<p>Thanks for the heads-up! Iâ€™m a bit puzzled since we havenâ€™t added any new dependencies, except for the test case within the dev group.</p>\n<p>I recall there was an issue with Poetry last time, and something had to be adjusted on the conda-forge side to make it work. Itâ€™s possible that the <code>recipe/meta.yml</code> file doesnâ€™t include those previous changes, which could be causing the failure. Iâ€™ll look into it further</p>",
        "id": 476906880,
        "sender_full_name": "Jan Range",
        "timestamp": 1728973005
    }
]