[
    {
        "content": "<p>Hi! Sorry if I am wrong here (Newbie) and feel free to push me to the right chat channel, but this seemed the most fitting: </p>\n<p>I am trying to test dataverse with the docker installation on a test server. On starting the containers I get the Payara standard screen displayed, after entering the admin interface at :4848 and clicking \"reload\" I get The Dataverse Project displayed, but with a 404-page not found, and no menues etc. I am using v6.0 of dataverse and put the endpoint to 8081 from 8080 due to that port not being available on my server.</p>\n<p>Any suggestions where to start debugging?</p>",
        "id": 409374546,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1703160544
    },
    {
        "content": "<p>Hmm, it should be possible to run on a port other than 8080 but I haven't tested it recently. Would it be possible to try again on 8080? I would suggest deleting the docker-dev-volumes directory first for a clean start (that's where the database, etc. is kept).</p>",
        "id": 409578940,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1703250007
    },
    {
        "content": "<p>Thanks for creating the new chat! Sorry, it took me a while to realize. I tried launching the containers on 8080 now (after deleting dev-volumes), but got the same result - Payara page on startup, and 404 Dataverse page after relaunch in the admin interface. Am I too impatient?</p>",
        "id": 410114559,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1703662471
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"675921\">@Jutta Schnabel</span> hi! It's my first day back after a long break. Did you get it working? Are you interested in joining our weekly meeting? (Please see <a class=\"stream-topic\" data-stream-id=\"375812\" href=\"/#narrow/stream/375812-containers/topic/weekly.20meeting\">#containers &gt; weekly meeting</a> .)</p>",
        "id": 411174334,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1704368530
    },
    {
        "content": "<p>Hi and thanks for the hints. Unfortunately, moving to 8080 and deleting the dev-volumes did not solve the problem, the behaviour is as observed before, so I went back to the other port. Thanks for the hint to the meeting, I would drop in and listen in to your activities, perhaps that helps me getting a better idea :)</p>",
        "id": 411187307,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1704374076
    },
    {
        "content": "<p>Great! We'd love for you to join!</p>",
        "id": 411188766,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1704374750
    },
    {
        "content": "<div class=\"codehilite\"><pre><span></span><code>dev_dataverse           |   Context path from ServletContext:  differs from path from bundle: /|#]\ndev_dataverse           |\ndev_dataverse           | [#|2024-01-04T15:25:31.315+0000|INFO|Payara 6.2023.8||_ThreadID=81;_ThreadName=http-thread-pool::http-listener-1(4);_TimeMillis=1704381931315;_LevelValue=800;|\ndev_dataverse           |   Loaded [1] org.ocpsoft.rewrite.spi.GlobalParameterProvider [org.ocpsoft.rewrite.instance.WildcardParameterProvider&lt;0&gt;]|#]\ndev_dataverse           |\ndev_bootstrap           | curl: (6) Could not resolve host: dataverse\ndev_bootstrap exited with code 6\n``\n</code></pre></div>",
        "id": 411209268,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1704381977
    },
    {
        "content": "<p>Docker version: Docker version 24.0.7</p>",
        "id": 411209553,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1704382062
    },
    {
        "content": "<p>Thanks. As I mentioned, it works in Ubuntu when spun up by GitHub Actions. For example: <a href=\"https://github.com/gdcc/api-test-runner/actions/runs/7185003205/job/19567333935\">https://github.com/gdcc/api-test-runner/actions/runs/7185003205/job/19567333935</a></p>\n<p>I'm not sure what the difference is. <span aria-label=\"thinking\" class=\"emoji emoji-1f914\" role=\"img\" title=\"thinking\">:thinking:</span></p>",
        "id": 411210591,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1704382397
    },
    {
        "content": "<p>Morning! <span class=\"user-mention\" data-user-id=\"675921\">@Jutta Schnabel</span> have you figured out what the problem is? I am a lot closer (timezone-wise) to you than <span class=\"user-mention\" data-user-id=\"598112\">@Philip Durbin</span>, happy to help.</p>",
        "id": 411680390,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1704697042
    },
    {
        "content": "<p>Hi! Thanks <span class=\"user-mention\" data-user-id=\"598183\">@Oliver Bertuch</span> for the offer! I just tried the installation now locally on my machine but interestingly I ended up with exactly the same error. So it might actually not be the server setup which is the problem.</p>\n<p>I used the current repo version, Docker 24.0.7 on ubuntu 22.04 (the server runs 20.04)<br>\n<a href=\"/user_uploads/53090/AWOPLmY-0xhl17-CYj4e7GDv/image.png\">image.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/53090/AWOPLmY-0xhl17-CYj4e7GDv/image.png\" title=\"image.png\"><img src=\"/user_uploads/53090/AWOPLmY-0xhl17-CYj4e7GDv/image.png\"></a></div>",
        "id": 411722026,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1704714136
    },
    {
        "content": "<p>Hi <span class=\"user-mention\" data-user-id=\"675921\">@Jutta Schnabel</span> ! At least it looks like you can access Dataverse now and not just see the Payara default domain page!</p>",
        "id": 411722188,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1704714217
    },
    {
        "content": "<p>When opening localhost, the docker output is the following: <br>\n<a href=\"/user_uploads/53090/zQQikKYNfxApV3_XUSrwP_3i/image.png\">image.png</a></p>\n<div class=\"message_inline_image\"><a href=\"/user_uploads/53090/zQQikKYNfxApV3_XUSrwP_3i/image.png\" title=\"image.png\"><img src=\"/user_uploads/53090/zQQikKYNfxApV3_XUSrwP_3i/image.png\"></a></div>",
        "id": 411722203,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1704714225
    },
    {
        "content": "<p>Oh yeah that one is not to worry about - this is normal during the first bootstrap. Could you share the output of conigbaker?</p>",
        "id": 411722341,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1704714270
    },
    {
        "content": "<p>I see the default 404, but this was also the case before when doing a relaunch from the admin interface on the server</p>",
        "id": 411722356,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1704714276
    },
    {
        "content": "<p>How can I get that output?</p>",
        "id": 411722420,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1704714308
    },
    {
        "content": "<p>But you see a 404 in the layout of Dataverse - not just Payara. Which means the app at least deployed succesfully</p>",
        "id": 411722425,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1704714310
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"675921\">Jutta Schnabel</span> <a href=\"#narrow/stream/375812-containers/topic/docker.20on.20test.20server/near/411722420\">said</a>:</p>\n<blockquote>\n<p>How can I get that output?</p>\n</blockquote>\n<p>Depending on how you started your container, use <code>docker logs</code>. You can find out the container name using <code>docker container ls -a</code>, because it will probably be stopped already.</p>",
        "id": 411722603,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1704714375
    },
    {
        "content": "<p>Interestingly I have three instances of that container, but only the first one has log content. In a repetitive fashon it contains</p>\n<div class=\"codehilite\"><pre><span></span><code>2024-01-08T11:30:40Z ERR Expectation failed error=&quot;failed to establish an http connection, caused by: Get \\&quot;http://dataverse:8080/api/info/version\\&quot;: dial tcp 172.21.0.10:8080: connect: connection refused&quot; address=http://dataverse:8080/api/info/version\n2024-01-08T11:30:48Z INF [HTTP] Checking the http://dataverse:8080/api/info/version ...\n2024-01-08T11:30:51Z ERR Expectation failed error=&quot;timed out while making an http call, caused by: Get \\&quot;http://dataverse:8080/api/info/version\\&quot;: context deadline exceeded (Client.Timeout exceeded while awaiting headers)&quot; timeout=3s\n2024-01-08T11:30:59Z INF [HTTP] Checking the http://dataverse:8080/api/info/version ...\n2024-01-08T11:30:59Z ERR Expectation failed error=&quot;the status code doesn&#39;t expect&quot; actual=404 expect=200\n2024-01-08T11:31:07Z INF [HTTP] Checking the http://dataverse:8080/api/info/version ...\n2024-01-08T11:31:10Z ERR Expectation failed error=&quot;timed out while making an http call, caused by: Get \\&quot;http://dataverse:8080/api/info/version\\&quot;: context deadline exceeded (Client.Timeout exceeded while awaiting headers)&quot; timeout=3s\n2024-01-08T11:31:18Z INF [HTTP] Checking the http://dataverse:8080/api/info/version ...\n2024-01-08T11:31:21Z ERR Expectation failed error=&quot;timed out while making an http call, caused by: Get \\&quot;http://dataverse:8080/api/info/version\\&quot;: context deadline exceeded (Client.Timeout exceeded while awaiting headers)&quot; timeout=3s\n2024-01-08T11:31:29Z INF [HTTP] Checking the http://dataverse:8080/api/info/version ...\n2024-01-08T11:31:29Z ERR Expectation failed error=&quot;the status code doesn&#39;t expect&quot; actual=404 expect=200\n</code></pre></div>",
        "id": 411723355,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1704714652
    },
    {
        "content": "<p>Yeah, that is expected - it waits in the background for Dataverse to deploy, so it can reach out and do it's magic to bootstrap the instance (add a superuser, add metadata blocks and create root collection)</p>",
        "id": 411723538,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1704714730
    },
    {
        "content": "<p>What I don't see is that it actually comes around to doing sth</p>",
        "id": 411723558,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1704714744
    },
    {
        "content": "<p>No timeout, too...</p>",
        "id": 411723589,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1704714758
    },
    {
        "content": "<p>I assume you have at least &gt;8 GB of RAM in your box, aye?</p>",
        "id": 411723704,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1704714812
    },
    {
        "content": "<p>Not in a box, but total RAM is 8GB</p>",
        "id": 411724003,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1704714945
    },
    {
        "content": "<p>That <em>should</em> be enough.</p>",
        "id": 411724260,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1704715047
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"675921\">@Jutta Schnabel</span>  Do you want to do a quick Zoom chat and let me take a look at live logs?</p>",
        "id": 411724325,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1704715080
    },
    {
        "content": "<p>yes, thanks: <a href=\"https://fau.zoom-x.de/j/65435375286\">https://fau.zoom-x.de/j/65435375286</a></p>",
        "id": 411724522,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1704715146
    },
    {
        "content": "<p>OK the problem with no bootstrapping happening is REALLY tricky</p>",
        "id": 411736037,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1704719710
    },
    {
        "content": "<p>We dug into this and turns out: <code>curl</code> doesn't like the way DNS was set up in her environment</p>",
        "id": 411736087,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1704719738
    },
    {
        "content": "<p>Thanks a lot for the great help! Whatever the problem was is yours to report ;)</p>",
        "id": 411736093,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1704719742
    },
    {
        "content": "<p>I did a bootstrap manually now by circumventing the DNS lookup (provided the Dataverse URL as command argument)</p>",
        "id": 411736229,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1704719780
    },
    {
        "content": "<p>When I find some time (but happy for someone else to pick up the task), I would like to have some vanilla Ubuntu 22.04 installed on a VM, get Docker on top and see if we can reproduce the problem</p>",
        "id": 411736364,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1704719834
    },
    {
        "content": "<p>Is it ok if I take the containers down and restart with endpoint 8081? It clashes with one of the other services now ...</p>",
        "id": 411736457,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1704719873
    },
    {
        "content": "<p>We exec'ed into configbaker and <code>nslookup</code>, <code>ping</code>, etc all were fine, just <code>curl</code> didn't want to cooperate. We saw it reaching out to the DNS server. Maybe a <code>tcpdump</code> would have helped, too, to analyze what goes over the wire.</p>",
        "id": 411736598,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1704719922
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"675921\">Jutta Schnabel</span> <a href=\"#narrow/stream/375812-containers/topic/docker.20on.20test.20server/near/411736457\">said</a>:</p>\n<blockquote>\n<p>Is it ok if I take the containers down and restart with endpoint 8081? It clashes with one of the other services now ...</p>\n</blockquote>\n<p>Yes, that should be fine</p>",
        "id": 411736626,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1704719932
    },
    {
        "content": "<p>I just renamed the topic so we can dig more into it later</p>",
        "id": 411736727,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1704719989
    },
    {
        "content": "<p>Please create a new topic for more questions that might arise, thx <span class=\"user-mention\" data-user-id=\"675921\">@Jutta Schnabel</span></p>",
        "id": 411736809,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1704720006
    },
    {
        "content": "<p>Will do, and thanks again for the deep dive!</p>",
        "id": 411736878,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1704720039
    },
    {
        "content": "<p>We were not in Texas but still deep into the heart of configbaker... <span aria-label=\"see no evil\" class=\"emoji emoji-1f648\" role=\"img\" title=\"see no evil\">:see_no_evil:</span></p>",
        "id": 411736995,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1704720086
    },
    {
        "content": "<p>btw., the restart now again only displayed the payara screen, but relaunch gave the working application</p>",
        "id": 411738068,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1704720509
    },
    {
        "content": "<p>Would it be premature to create an issue to track this problem? We'd like to reproduce it first?</p>",
        "id": 411758875,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1704727114
    },
    {
        "content": "<p>It looks like this is related to this PR, that has been merged recently. <a href=\"https://github.com/c-ares/c-ares/pull/685\">https://github.com/c-ares/c-ares/pull/685</a>. See this issue: <a href=\"https://github.com/c-ares/c-ares/issues/683\">https://github.com/c-ares/c-ares/issues/683</a></p>\n<p>cURL on Alpine uses c-ares for DNS resolution as of alpine 3.19. As we are using <code>alpine:3</code> as our base image, we are on 3.19. The fixed version of c-ares has been released, but the last build of curl dates back to 12.2023 (<a href=\"https://pkgs.alpinelinux.org/packages?name=curl&amp;branch=v3.19\">https://pkgs.alpinelinux.org/packages?name=curl&amp;branch=v3.19</a>)</p>\n<p>So probably two options: we tag our base with 3.18 or we wait for a new release. I wouldn't go for the \"edge\" package.</p>",
        "id": 428348715,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1711119439
    },
    {
        "content": "<p>Interesting. So downgrade to Alpine 3.18 and leave a comment saying \"don't upgrade to 3.19 or beyond until the version of curl is built with a version of c-ares that has a fix for <a href=\"https://github.com/c-ares/c-ares/issues/683\">https://github.com/c-ares/c-ares/issues/683</a> \"</p>\n<p>Something like that? I can't easily tell which version of curl has the fix.</p>",
        "id": 428350936,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1711120050
    },
    {
        "content": "<p>3.19 still is on c-ares 1.24. See <a href=\"https://pkgs.alpinelinux.org/package/v3.19/main/x86_64/c-ares\">https://pkgs.alpinelinux.org/package/v3.19/main/x86_64/c-ares</a></p>",
        "id": 428351389,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1711120189
    },
    {
        "content": "<p>Edge has c-ares 1.26.0, containing the fix <a href=\"https://pkgs.alpinelinux.org/package/edge/main/x86/c-ares\">https://pkgs.alpinelinux.org/package/edge/main/x86/c-ares</a></p>",
        "id": 428351532,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1711120223
    },
    {
        "content": "<p>Curl in Alpine 3.18 does not have the c-ares dependency, see <a href=\"https://pkgs.alpinelinux.org/package/v3.18/main/x86_64/libcurl\">https://pkgs.alpinelinux.org/package/v3.18/main/x86_64/libcurl</a></p>",
        "id": 428351673,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1711120264
    },
    {
        "content": "<p><a href=\"https://github.com/IQSS/dataverse/issues/10413\">https://github.com/IQSS/dataverse/issues/10413</a></p>",
        "id": 428352711,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1711120569
    },
    {
        "content": "<p>Ok, bottom line for the issue you opened is to downgrade to Alpine 3.18. Sounds good.</p>",
        "id": 428353353,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1711120758
    },
    {
        "content": "<p>I'm way ahead</p>",
        "id": 428353570,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1711120813
    },
    {
        "content": "<p>Do we know which version of curl has the fix?</p>",
        "id": 428353580,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1711120816
    },
    {
        "content": "<p>PR in 3 ...</p>",
        "id": 428353599,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1711120822
    },
    {
        "content": "<p>ha</p>",
        "id": 428353619,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1711120826
    },
    {
        "content": "<p><a href=\"https://github.com/IQSS/dataverse/pull/10414\">https://github.com/IQSS/dataverse/pull/10414</a></p>",
        "id": 428354006,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1711120932
    },
    {
        "content": "<p>just left a review, thanks!</p>",
        "id": 428354840,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1711121175
    },
    {
        "content": "<p>I just saw that they did a backport for 3.19... See <a href=\"https://git.alpinelinux.org/aports/commit/?id=6edd0d6d61c7f8b8a37e84333b37aa02e6507bfb\">https://git.alpinelinux.org/aports/commit/?id=6edd0d6d61c7f8b8a37e84333b37aa02e6507bfb</a></p>",
        "id": 428356979,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1711121728
    },
    {
        "content": "<p>Suggestions: if 3.18 works, lets see if we can make <span class=\"user-mention\" data-user-id=\"598843\">@Deirdre Kirmis</span> look how old her local image pull is. (<code>docker image ls \"gdcc/*\"</code>)</p>",
        "id": 428357195,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1711121784
    },
    {
        "content": "<p>That commit is two months from what I can tell.</p>",
        "id": 428357802,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1711121976
    },
    {
        "content": "<p>Yeah, it's from 2024-01-23</p>",
        "id": 428358112,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1711122063
    },
    {
        "content": "<p>yes ^</p>",
        "id": 428358905,
        "sender_full_name": "Deirdre Kirmis",
        "timestamp": 1711122298
    },
    {
        "content": "<p>Yes? As in \"my image is that old\"?</p>",
        "id": 428359162,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1711122374
    },
    {
        "content": "<p>At least I can tell that the problems <span class=\"user-mention\" data-user-id=\"675921\">@Jutta Schnabel</span> experienced were from <em>before</em> that backport happened</p>",
        "id": 428359587,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1711122507
    },
    {
        "content": "<p>From the debugging I did with <span class=\"user-mention\" data-user-id=\"598843\">@Deirdre Kirmis</span> at <a class=\"stream-topic\" data-stream-id=\"375812\" href=\"/#narrow/stream/375812-containers/topic/demo.20tutorial.20issues\">#containers &gt; demo tutorial issues</a> I learned that the \"fix\" they made in c-ares does not really fix it. Will report there.</p>",
        "id": 428367248,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1711124766
    },
    {
        "content": "<p><a href=\"https://github.com/c-ares/c-ares/issues/683#issuecomment-2015471931\">https://github.com/c-ares/c-ares/issues/683#issuecomment-2015471931</a></p>",
        "id": 428369149,
        "sender_full_name": "Oliver Bertuch",
        "timestamp": 1711125319
    }
]