[
    {
        "content": "<p>Another PS: In the installation now when trying to upload a file through the web interface, the file is not staged (similar to the issue described here: <a href=\"https://groups.google.com/g/dataverse-community/c/7pbPBOnix7M/m/ZIznjSFqAwAJ\">https://groups.google.com/g/dataverse-community/c/7pbPBOnix7M/m/ZIznjSFqAwAJ</a>), so no file upload is possible. Not sure if that is related?</p>",
        "id": 412363849,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1704985838
    },
    {
        "content": "<p>Weird. Any errors in Payara's server.log? You could try <code>docker logs dataverse-1</code> (I think it's dataverse-1. You can do a <code>docker ps</code> to get the name of the container.)</p>",
        "id": 412367388,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1704986852
    },
    {
        "content": "<p>Sorry, again missed the reply due to the move to the new channel, and thanks for the hint: it says \"Temp directory is not configured.\"</p>",
        "id": 412597951,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1705083841
    },
    {
        "content": "<p>and before \"Failed to create filesTempDirectory: /dv/temp\"</p>",
        "id": 412598069,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1705083874
    },
    {
        "content": "<p>The /dv-folder exists but creating a subfolder is not permitted (also not manually). There is no /dv/temp.</p>",
        "id": 412599566,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1705084466
    },
    {
        "content": "<p>Hmm, yes, that would explain why you can't upload files.</p>",
        "id": 412602750,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705085742
    },
    {
        "content": "<p>Can you mount /dv differently, with write permission?</p>",
        "id": 412602839,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705085770
    },
    {
        "content": "<p>I'm not sure why you're seeing this. <span aria-label=\"thinking\" class=\"emoji emoji-1f914\" role=\"img\" title=\"thinking\">:thinking:</span></p>",
        "id": 412602868,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705085783
    },
    {
        "content": "<p>I tried a chmod, but it is not permitted</p>",
        "id": 412605530,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1705086950
    },
    {
        "content": "<p>entered the container now as root, changed to write permissions on /dv and added a /temp, but now the new error is \"Failed to process and/or save the file km3net_logo_trans.png; /dv/temp/tmp16526284070961205053upload\"</p>",
        "id": 412606747,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1705087494
    },
    {
        "content": "<p>OK, now I manually created /dv/temp from root, changed permission to a+w, and now it works</p>",
        "id": 412607696,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1705087898
    },
    {
        "content": "<p>Oh, great!</p>",
        "id": 412607757,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705087911
    },
    {
        "content": "<p>But what happens the next time you spin up Dataverse in Docker? You'd have to do those steps manually?</p>",
        "id": 412607870,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705087941
    },
    {
        "content": "<p>I hope not :) Anyhow, with the changes from Oliver I try not to touch the containers again...</p>",
        "id": 412608099,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1705088033
    },
    {
        "content": "<p>Thanks again for the help!</p>",
        "id": 412608335,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1705088116
    },
    {
        "content": "<p>Sure. I wonder what's different about your setup. I'm on a Mac and it works fine. The test runners in GitHub Actions are Ubuntu and it works fine.</p>",
        "id": 412608367,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705088130
    },
    {
        "content": "<p>The main place where we're seeing problems in this area is Windows.</p>",
        "id": 412608618,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705088225
    },
    {
        "content": "<p>I am not so deep into containers, so not sure where the permission problems come from</p>",
        "id": 412608710,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1705088265
    },
    {
        "content": "<p>Yeah, me neither. <span aria-label=\"sweat smile\" class=\"emoji emoji-1f605\" role=\"img\" title=\"sweat smile\">:sweat_smile:</span></p>",
        "id": 412608799,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705088292
    },
    {
        "content": "<p>Could still hope that it's only an issue because there is something strange in my setup...</p>",
        "id": 412608916,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1705088344
    },
    {
        "content": "<p>well, the celebration was premature. Staging now works, but saving not - \"Error. Failed to add files to dataset ...\"</p>",
        "id": 412612483,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1705089862
    },
    {
        "content": "<p>The error: \"java.lang.RuntimeException: Error creating temp directory\" and \"failed to save the file\"</p>",
        "id": 412612802,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1705090014
    },
    {
        "content": "<p>Summary: After changing the permissions not only in /dv/temp but also for /dv to all, storage of the file works (in /dv/store). The java exception was caused by trying to upload a logo for the theme.</p>",
        "id": 412614177,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1705090701
    },
    {
        "content": "<p>A theme for a collection/dataverse, I suppose.</p>",
        "id": 412614733,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705090991
    },
    {
        "content": "<p>for the root dataverse, yes.</p>",
        "id": 412615464,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1705091341
    },
    {
        "content": "<p>There are probably even more places where temp directories are created so we should fix this. <span aria-label=\"sweat smile\" class=\"emoji emoji-1f605\" role=\"img\" title=\"sweat smile\">:sweat_smile:</span></p>",
        "id": 412615760,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705091459
    },
    {
        "content": "<p>I'm hoping one of the people who know Docker better (Oliver or Guillermo) can help next week.</p>",
        "id": 412615857,
        "sender_full_name": "Philip Durbin ðŸš€",
        "timestamp": 1705091490
    },
    {
        "content": "<p>Thanks! So far we can live with the dataverse logo <span aria-label=\"wink\" class=\"emoji emoji-1f609\" role=\"img\" title=\"wink\">:wink:</span></p>",
        "id": 412616168,
        "sender_full_name": "Jutta Schnabel",
        "timestamp": 1705091627
    }
]